# Generated by Django 5.1.4 on 2025-01-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_post_created_at_alter_post_img_url"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="slug",
            field=models.SlugField(default="timez"),
            preserve_default=False,
        ),
    ]
